name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
          aws ec2 run-instances \
            --image-id ami-053b0d53c279acc90 \
            --instance-type t2.micro \
            --key-name mykeyaws \
            --security-group-ids sg-09be710243a70d85b \
            --user-data '#!/bin/bash \
                          curl -LO https://github.com/Atifkarim121/deploy-java-githubaction/releases/latest/download/myapp.jar \
                          java -jar myapp.jar'
